### ISSUE TITLE
Evaluate stuck after some executions in headless mode

### ISSUE THREAD

**Issue by alternativshik** [pyppeteer/pyppeteer#137] opened 2020-06-16 06:49 UTC
if I call this code 100-200 times it just stuck and still awaiting forever:

`
await self.page.evaluate('''() => {
    console.log('LOG');
    return 'test string';
}''')
`
Any Ideas? This goes only with headless: True option on all chrome and chromium builds under macOS and Linux, but on NodeJS puppeteer same code works perfect.

**Comment by alternativshik** [comment] 2020-06-16 06:59
It freezes always on 743 calls

**Comment by Mattwmaster58** [comment] 2020-06-16 19:57
Wow, exactly 743 calls? Or just around there?

**Comment by alternativshik** [comment] 2020-06-17 04:25
Depends on Chrome version. On System chrome 792, downloaded chromium - 743 :-D
And I have no idea how to debug this.

**Comment by Mattwmaster58** [comment] 2020-06-17 21:48
I tested with up too 8000 iterations of the aforementioned statement to no effect, can you repeatable reproduce your 743 figure?

**Comment by alternativshik** [comment] 2020-06-18 12:14
> I tested with up too 8000 iterations of the aforementioned statement to no effect, can you repeatable reproduce your 743 figure?

It's repeatable reproduce on 3 different devices. Also, I don't close browser after each call.

**Comment by Mattwmaster58** [comment] 2020-06-19 01:32
I'm not closing the browser either. I suspect this has something to do with an outdated chrome client.

**Comment by Mattwmaster58** [comment] 2020-06-20 22:00
It's possible the Chromium version bundled with the last version is old enough to cause problems.

**Comment by alternativshik** [comment] 2020-06-21 07:01
> It's possible the Chromium version bundled with the last version is old enough to cause problems.

I've tested this with the latest system Chrome version - has the same issue - freeze after some nums of requests

**Comment by Mattwmaster58** [comment] 2020-06-22 03:45
Hmm, you could try the best version by installing from the pup2.1.1 branch, or, you could try finding the debug logs

**Comment by jessrosenfield** [comment] 2020-06-24 04:35
I get this error as well. I also tried running using the pup2.1.1 branch (in addition to some refactoring of my own calls when switching to this branch, I changed the line here [here](https://github.com/pyppeteer/pyppeteer/blob/pup2.1.1/pyppeteer/domworld.py#L55) to `self.loop.create_task(waitTask.rerun())` to get it to work w/ my code). Here's a gist with the last few debug logs: https://gist.github.com/jessrosenfield/e4e9717955e9a886c795cdd0238e825b

This is using the default revision of Chrome (revision 722234 for mac). The place where it times out is in a loop for visiting a list of pages. If I shuffle the list I still get this error at roughly 12-15 pages in. Visiting a single page works successfully.

**Comment by Mattwmaster58** [comment] 2020-06-24 05:09
@jessrosenfield thanks for the logs, in general it would be a little more helpful to narrow down logging to just pyppeteer, but this is enough to work with for now.

Without exact code to reproduce, I really have no idea what's wrong here. I've run into issues before where even with side by side with puppeteer logs it took me hours to track down the root of the issue and resolve it, so without a clear way to reproduce the issue it's gonna quite difficult to pin it down.

That being I'm said there's a few more things you can try: 
- narrow down debug logs to just pyppeteer
- manually specify or place the version of chromium used with the release tagged v2.1.1 puppeteer
- post more logs, around the last 50 lines should do it
- make sure you have the latest puo2.1.1 changes

And if you are really, really are feeling adventurous/desperate/whatever you could try and run the same script in puppeteer and pyppeteer and diff logs to look for discrepancies. But that can be quite time consuming.

**Comment by Mattwmaster58** [comment] 2020-06-24 05:10
@alternativshik Could you provide some - system details?

**Comment by alternativshik** [comment] 2020-06-24 06:26
> @alternativshik Could you provide some - system details?

Latest stable MacOS with latest python 3.8 from brew with both included Chromium and system latest Chrome. Also, same issue was on Ubuntu 18.04 with python 3.8 with bundled Chromium

**Comment by jessrosenfield** [comment] 2020-06-24 13:06
@Mattwmaster58 I edited my comment to clarify that I'm using Chromium revision 722234. To test this bug I ran `pip install git+https://github.com/pyppeteer/pyppeteer@pup2.1.1` yesterday so it would have pulled from 75ab61b573332822e3bf9a6c14422fdc9e3c289e. I'm running MacOS 10.15.4 and used Python 3.7.7.

Also here are logs in a similar fashion using the v0.2.2 release: https://gist.github.com/jessrosenfield/2d3ad1a5c0fa5522476a5d706e258ea5

I'll rerun w/ pup2.1.1 and output the last 50 lines w/out the websocket logs.

**Comment by Mattwmaster58** [comment] 2020-06-24 13:27
@jessrosenfield that might very well be the issue here! I'll take a deeper look later, and if you want to submit a pr against pup2.1.1 that would be great as well.

**Comment by jessrosenfield** [comment] 2020-06-24 14:19
@Mattwmaster58 what might be the issue here? I'm not sure I follow.
Also, here are the logs you asked for: https://gist.github.com/jessrosenfield/77f4290eec9a7500770cf39afcd2a0e1

**Comment by jessrosenfield** [comment] 2020-06-24 14:22
If you're referring to the `self.loop.create_task(waitTask.rerun())` patch, I still got the error with this patch and just wanted to clarify that I didn't run the code completely as-is. I'll open a PR though!

**Comment by jessrosenfield** [comment] 2020-06-24 15:23
Also, I forgot to add that I do not encounter this error with the setting `headless=False`.

**Comment by jessrosenfield** [comment] 2020-06-24 15:25
Here are the launch options used for the logs I gave you (this does not use `ignoreDefaultArgs` so this is in addition to default args):
```
launch_options = {
    'headless': True,
    'defaultViewport': {'width': 1200, 'height': 800},
    'args': [
        # These chrome flags were derived from chrome-aws-lambda
        # https://github.com/alixaxel/chrome-aws-lambda/blob/master/source/index.js
        '--autoplay-policy=user-gesture-required',
        '--disable-background-networking',
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-client-side-phishing-detection',
        '--disable-component-update',
        '--disable-default-apps',
        '--disable-dev-shm-usage',
        '--disable-domain-reliability',
        '--disable-extensions',
        '--disable-features=AudioServiceOutOfProcess',
        '--disable-hang-monitor',
        '--disable-ipc-flooding-protection',
        '--disable-notifications',
        '--disable-offer-store-unmasked-wallet-cards',
        '--disable-popup-blocking',
        '--disable-print-preview',
        '--disable-prompt-on-repost',
        '--disable-renderer-backgrounding',
        '--disable-setuid-sandbox',
        '--disable-speech-api',
        '--disable-sync',
        '--disk-cache-size=33554432',
        '--hide-scrollbars',
        '--ignore-gpu-blacklist',
        '--metrics-recording-only',
        '--mute-audio',
        '--no-default-browser-check',
        '--no-first-run',
        '--no-pings',
        '--no-sandbox',
        '--no-zygote',
        '--password-store=basic',
        '--use-mock-keychain',

        # Additional flags
        '--single-process',
        '--disable-gpu',
        '--disable-dev-profile',
    ],
    'logLevel': logging.DEBUG,
    'userDataDir': '/tmp',
}
```

**Comment by stardund** [comment] 2020-07-23 19:52
can confirm this issue - my pyppeteer script in headless: True gets simply stuck and does nothing (happens always and on the first try), while in headless: False it works fine.

I have written exactly the same code in puppeteer too and there it works fine in headless.

I have also tried to set the chromium executablePath to the one that gets bundled with the latest puppeteer release, unfortunately in pyppeteer headless it still gets stuck and does nothing, so old chromium version has probably nothing with this

**Comment by samsouk** [comment] 2020-08-01 12:41
Hi,
I'm not sure it is the same issue, but it might help: I've observed the frozen symptom on few sites with bad behaviours, and I've noticed it could be solved by activating the `dumpio` option.
Then it became too verbose, so  I've patched the `pyppeteer/launcher.py` file

my guess is that the `subprocess.Popen` freezes when the STDERR is flooded (which can happen if you don't consume stderr)

Original code, `pyppeteer/launcher.py` line 140

```
        options = dict()
        options['env'] = self.env
        if not self.dumpio:
            options['stdout'] = subprocess.PIPE
            options['stderr'] = subprocess.STDOUT

        self.proc = subprocess.Popen(  # type: ignore
            self.cmd, **options, )
```

as I don't need the STDERR on production, I've sent it to /dev/null (and I don't use dumpio anymore)

changed `pyppeteer/launcher.py` line 144:

```
             options['stderr'] = subprocess.DEVNULL
```

**Comment by alternativshik** [comment] 2020-08-06 07:43
> Hi,
> I'm not sure it is the same issue, but it might help: I've observed the frozen symptom on few sites with bad behaviours, and I've noticed it could be solved by activating the `dumpio` option.
> Then it became too verbose, so I've patched the `pyppeteer/launcher.py` file
> 
> my guess is that the `subprocess.Popen` freezes when the STDERR is flooded (which can happen if you don't consume stderr)
> 
> Original code, `pyppeteer/launcher.py` line 140
> 
> ```
>         options = dict()
>         options['env'] = self.env
>         if not self.dumpio:
>             options['stdout'] = subprocess.PIPE
>             options['stderr'] = subprocess.STDOUT
> 
>         self.proc = subprocess.Popen(  # type: ignore
>             self.cmd, **options, )
> ```
> 
> as I don't need the STDERR on production, I've sent it to /dev/null (and I don't use dumpio anymore)
> 
> changed `pyppeteer/launcher.py` line 144:
> 
> ```
>              options['stderr'] = subprocess.DEVNULL
> ```

Yep, this works for me

**Comment by Mattwmaster58** [comment] 2020-08-06 21:02
@samsouk 
> my guess is that the subprocess.Popen freezes when the STDERR is flooded (which can happen if you don't consume stderr)

I should look into this. Thanks for the heads up.

**Comment by hukasu** [comment] 2020-08-24 14:53
I have a long chain of selects (the form have many dropdown fields), and some of the selects have a onChange event to load the values of the next select, so i have a waitForFunction waiting for the mutation of the object of the onChange, and it hangs at this point.  
Doing the @samsouk change to DEVNULL fixes the hang for me too.

**Comment by jtf9808** [comment] 2020-08-26 08:41
I have had a similar Issue to @alternativshik but using page.goto(). The @samsouk solution fixed it!

**Comment by AndreiRegiani** [comment] 2020-12-05 21:47
@samsouk solution worked for me too! `options['stderr'] = subprocess.DEVNULL`

I think this hotfix **urgently needs to be the default and released on PyPi ASAP**, as right now Pyppeteer is unstable for production with this hidden bug which only late in development you find out, maybe I did something wrong on my setup but that was my experience running dozens of instances 24/7 and having to babysit them all day long.

**Comment by Mattwmaster58** [comment] 2020-12-05 22:32
You're right, I'm in the process of pushing a hotfix release @AndreiRegiani @alternativshik.

**Comment by Mattwmaster58** [comment] 2020-12-05 22:57
https://github.com/pyppeteer/pyppeteer/tree/0.2.3 is likely what this release will look like. Please bear with us as we work to release it (I'll be honest, I lost my PyPi 2FA codes :| )

**Comment by AndreiRegiani** [comment] 2020-12-06 17:54
Nice! just to confirm the good news, after that small fix I didn't get a single freeze anymore, tested by running 20 headless instances for the last 24 hours on a Ubuntu VPS.

It seems that on high-end PCs (during development) this issue doesn't show up as frequently, but on heavy load hosts it does.

**Comment by samsouk** [comment] 2020-12-07 18:24
great
I can't test it right now, but I'm running a pacthed 0.2.2 since months now (before my original comment), with 100k pages/day across different sites, and everything is smooth

**Comment by Mattwmaster58** [comment] 2020-12-29 21:50
@samsouk @AndreiRegiani @alternativshik A RC which includes a fix for this has been released: 0.2.3.rc1. Please let me know if this version is ~stable~ more stable than the last one.

**Comment by AndreiRegiani** [comment] 2021-01-02 22:03
This script can reproduce the issue, I tested with 3 stdout/stderr options:

```python3
import asyncio
from pyppeteer import launch

async def main():
    browser = await launch()
    page = await browser.newPage()
    await page.goto('https://google.com')

    for count, i in enumerate(range(10_000)):
        result = await page.evaluate('''() => { console.log('LOG'); return 'test string'; }''')
        print(count, result)

    await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

1) FREEZES: stops at: `733 test string` (pip pyppeteer==0.2.2)
```
options['stdout'] = subprocess.PIPE
options['stderr'] = subprocess.STDOUT
```
---
2) NO ISSUES, `9999 test string`, dev branch
```
options['stdout'] = subprocess.DEVNULL
options['stderr'] = subprocess.STDOUT
```
---
3) NO ISSUES, `9999 test string`
```
options['stdout'] = subprocess.PIPE
options['stderr'] = subprocess.DEVNULL
```

**Comment by AndreiRegiani** [comment] 2021-01-02 22:15
@Mattwmaster58 tested with a `1_000_000` loop and seems to be really fixed. Nice finding @alternativshik!

**Comment by Mattwmaster58** [comment] 2021-01-03 01:24
Just released 0.2.3 which includes a fix for this

**Closed as completed by Mattwmaster58** 2021-01-03 01:24 UTC
Labels: bug, fixed-in-2.1.1, can't reproduce

**Comment by samsouk** [comment] 2021-01-05 11:12
hi Mattwmaster58, thanks for the release,

Now I'm struggling with the pip release versions : https://pypi.org/project/pyppeteer/

we had these pip versions on our production environment:
* 0.0.25
* 0.2.2

And, few days ago, I've tested the last 0.2.3 pip release

now, I wonder what are the changes between 0.2.2 and 0.2.3, but couldn't find any 0.2.2 tag on this git repo

based on the 0.2.2 release date (May 8, 2020), I've supposed that it matches the ad3a0a7 commit (does it?)

**Comment by H--o-l** [comment] 2021-06-11 09:53
Hi @samsouk, I'm not a maintainer or anything else but I think I should tell you that before asking such a question you should :
- look for previous issues on the subject (closed and opened)
- open a new issue if you don't find one.

Here you are asking a question inside a "closed" issue, and a question that as nothing to do with the original question. 
You cannot expect to get an answer like that.

But, to answer you, I had the same question as you, I opened an issue, it's here:
https://github.com/pyppeteer/pyppeteer/issues/200

**Comment by samsouk** [comment] 2021-06-11 10:44
Hi @H--o-l , sorry for that,
and thanks for opening a new issue
