### ISSUE TITLE
Page goto returns None Even in Headmode

### ISSUE THREAD

**Issue by viKal767** [pyppeteer/pyppeteer#63] opened 2020-03-13 09:25 UTC
Hi,
For some URLs, the goto() does not fail, but still returns None. But when we process it later or after a no of retries, it returns correct response.

For example url:
       https://www.vitals.com/dentists/Dr_John_C_Paris.html

I  have used pyppeteer2 as well as pyppeteer with Python 3.6
Here is a minimal example
```
res = await page.goto(url, options={
                  "waitUntil": "domcontentloaded",
                  "timeout": 0
        })

if res is not None:
    # some processing done
else:
    # error raised
```

**Comment by Granitosaurus** [comment] 2020-03-13 11:39
Seems like a duplicate of https://github.com/pyppeteer/pyppeteer2/issues/60 

#16 should resolve this eventually.

**Closed as completed** 2020-03-13 13:13 UTC
Labels: duplicate

**Comment by viKal767** [comment] 2020-03-13 14:53
@Granitosaurus 
There wasn't any decoding problem or any kind of error. I think the problem was some how some urls might be loading from the browser's cache memory. So that causes an invalid navigation request and the page response will set as null.
This is just a wild guess. I don't have any proof.

**Comment by Mattwmaster58** [comment] 2020-03-13 18:09
@VishnuAtDevopStation The current implementation is outdated and being reworked along with everything in #16.

**Comment by Mattwmaster58** [comment] 2020-03-14 15:42
@VishnuAtDevopStation I can confirm that your example works as intended on the pup2.1.1 branch
