### ISSUE TITLE
The '__version__' is not defined with pyinstaller and latest pyppeteer

### ISSUE THREAD

**Issue by lanzorg** [pyppeteer/pyppeteer#213] opened 2021-01-24 10:24 UTC
I have this weird error when using pyinstaller (4.2) with pyppeteer (0.2.5).

```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "autotidote.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "downloader.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "pyppeteer\__init__.py", line 43, in <module>
NameError: name '__version__' is not defined
[8536] Failed to execute script main
```

I have the same error with pyppeteer (dev), but it's working fine with pyppeteer (0.2.4).

**Comment by Mattwmaster58** [comment] 2021-01-25 19:18
man, I hoped something like this wouldn't happen with the change I made in 0.2.5. Unfortunately it seems like the recommended way to 'sync' your pyproject.toml version with your package specified version. Probably could be argued to be pyppeteers or pyinstaller's bug either way

**Comment by Mattwmaster58** [comment] 2021-01-25 19:19
see here: https://github.com/pyppeteer/pyppeteer/pull/208

**Comment by nonewind** [comment] 2021-01-28 07:12
I had the same problem. 
I changed "__init__" in pyppeteer:

```
"""
try:
    __version__ = version(__name__)
except Exception:
    pass
"""
__version__="0.2.5"
```
then run "pyinstaller -F myfile.py" create .exe ! It's working now!!!!

**Comment by ThySpecter** [comment] 2021-02-11 20:48
> I had the same problem.
> I changed "**init**" in pyppeteer:
> 
> ```
> """
> try:
>     __version__ = version(__name__)
> except Exception:
>     pass
> """
> __version__="0.2.5"
> ```
> 
> then run "pyinstaller -F myfile.py" create .exe ! It's working now!!!!

This also worked for me

**Comment by VeNoMouS** [comment] 2021-04-01 01:27
The problem is that your "version" data is actually stored in the dist-info directory... you need to include that dir via `--add-data`

As an example

```python
 --add-data C:/python38/Lib/site-packages/pyppeteer-0.2.5.dist-info;pyppeteer-0.2.5.dist-info
 ```
 
 This is because `version` from `importlib` reads from the `METADATA` file...
 
 So the problem is the way `pyppeteer` has been packaged.

**Comment by fuji44** [comment] 2021-06-04 12:44
Using the `--copy-metadata` option, I was able to solve this problem without rewriting `__init__.py`.

```
pyinstaller --onefile run.py --copy-metadata pyppeteer
```

**Comment by Swapnil0115** [comment] 2021-08-13 08:29
> Using the `--copy-metadata` option, I was able to solve this problem without rewriting `__init__.py`.
> 
> ```
> pyinstaller --onefile run.py --copy-metadata pyppeteer
> ```

Thankyou SOo much!! This works

**Comment by Mattwmaster58** [comment] 2021-08-14 17:02
I'm going to consider this issue closed as a solution has been posted

**Closed as completed by Mattwmaster58** 2021-08-14 17:02 UTC

**Comment by bwoodsend** [comment] 2021-10-06 16:37
This bug is back. That particular access to `__version__` is still correctly guarded but it later gets referenced to set `version` and `version_info`.
https://github.com/pyppeteer/pyppeteer/blob/81ac20b46e4130c306ea193a2241f8d7ac5e1deb/pyppeteer/__init__.py#L39-L40

Those two lines should be moved into [the try/except block](https://github.com/pyppeteer/pyppeteer/blob/81ac20b46e4130c306ea193a2241f8d7ac5e1deb/pyppeteer/__init__.py#L18). 

See also [the corresponding issue on PyInstaller's issue tracker](https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/329#issuecomment-936619498).

**Comment by iscluis06** [comment] 2023-03-29 22:43
> Using the `--copy-metadata` option, I was able to solve this problem without rewriting `__init__.py`.
> 
> ```
> pyinstaller --onefile run.py --copy-metadata pyppeteer
> ```

Thank you so much!! you save me, I won't mind buying you a beer man!
